// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctqhzlqzrswrzarbfdpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0cWh6bHF6cnN3cnphcmJmZHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTkzNTgsImV4cCI6MjA2NTU3NTM1OH0.oxDroMFPJ7eLwmZ9LM1XBzpLTyggHm4RJ3AyaREhfPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);